[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
solc_version = "0.8.20"
fs_permissions = [{ access = "read-write", path = "."}]

[fuzz]
runs = 50
